In [10]:
import pandas as pd
import numpy as np
from pathlib import Path

In [13]:
ROOT = Path.cwd().parent

df_main = pd.read_csv(ROOT/"data/raw/osm_mcdonalds.csv")
df_main.head()

,element,id,name,brand,addr:street,addr:housenumber,addr:city,addr:postcode,phone,website,geometry,lat,lon
0,node,142773190,McDonald's,McDonald's,Rua Henrique Schaumann,124,São Paulo,05413-010,NaN,NaN,POINT (-46.6782804 -23.5633723),-23.563372,-46.678280
1,node,865280465,McDonald's,McDonald's,Avenida Bernardino de Campos,307,NaN,04004-050,0800 888 1955,https://www.mcdonalds.com.br/,POINT (-46.6422711 -23.573439),-23.573439,-46.642271
2,node,2195123498,McDonald's,McDonald's,Avenida Paulista,2034,São Paulo,01310-200,NaN,NaN,POINT (-46.6593523 -23.5585802),-23.558580,-46.659352
3,node,2428171364,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7024611 -23.5284532),-23.528453,-46.702461
4,node,2862747295,McDonald's,McDonald's,Rua Augusta,1858,São Paulo,01412-000,NaN,NaN,POINT (-46.6611783 -23.5588939),-23.558894,-46.661178

In [14]:
df_main.dtypes

element                 str
id                    int64
name                    str
brand                   str
addr:street             str
addr:housenumber        str
addr:city               str
addr:postcode           str
phone                   str
website                 str
geometry                str
lat                 float64
lon                 float64
dtype: object

In [15]:
df_main['id'] = df_main['id'].astype(str)

In [17]:
df_main[df_main['addr:street'].isna()]

,element,id,name,brand,addr:street,addr:housenumber,addr:city,addr:postcode,phone,website,geometry,lat,lon
3,node,2428171364,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7024611 -23.5284532),-23.528453,-46.702461
5,node,3383889645,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7198587 -23.4879365),-23.487936,-46.719859
7,node,4103925391,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7070513 -23.653066),-23.653066,-46.707051
12,node,4936395923,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.640467 -23.5427516),-23.542752,-46.640467
17,node,5887250288,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.4499546 -23.5406288),-23.540629,-46.449955
18,node,5894715989,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7008063 -23.5209359),-23.520936,-46.700806
19,node,5894770685,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.709787 -23.6531488),-23.653149,-46.709787
20,node,6216089070,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5996862 -23.5216264),-23.521626,-46.599686
21,node,6389931858,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.619423 -23.5896226),-23.589623,-46.619423
25,node,7177787341,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7122011 -23.6164626),-23.616463,-46.712201
27,node,9706142974,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6993834 -23.62381),-23.623810,-46.699383
28,node,9709143833,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6964571 -23.6091925),-23.609192,-46.696457
29,node,9709143862,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.697041 -23.6101532),-23.610153,-46.697041
30,node,9711875813,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6519975 -23.5542176),-23.554218,-46.651998
31,node,9717848310,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5770054 -23.5420048),-23.542005,-46.577005
32,node,9717887173,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5765546 -23.539136),-23.539136,-46.576555
33,node,10032623950,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7248619 -23.5859337),-23.585934,-46.724862
34,node,10922252874,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5809933 -23.5850739),-23.585074,-46.580993
36,node,11779572657,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7175217 -23.630248),-23.630248,-46.717522
37,node,11809589930,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5939182 -23.5795696),-23.579570,-46.593918
38,node,12732034241,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.5483412 -23.6018268),-23.601827,-46.548341
39,node,12849695500,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6187242 -23.5371165),-23.537116,-46.618724
40,node,12911126272,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6241362 -23.5217588),-23.521759,-46.624136
41,node,12950445773,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6988346 -23.6780168),-23.678017,-46.698835
42,node,12950445778,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6957372 -23.5724799),-23.572480,-46.695737
43,node,12986820698,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6101982 -23.4788203),-23.478820,-46.610198
44,node,13141297304,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.6756897 -23.5152326),-23.515233,-46.675690
46,node,13633992534,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7707745 -23.6660309),-23.666031,-46.770775
51,way,125998728,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6502638 -23.6020602, -46.6502749...",-23.602229,-46.650343
52,way,183798231,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6378059 -23.5827572, -46.6377623...",-23.582818,-46.637913
61,way,377622390,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6917295 -23.6551805, -46.6917177...",-23.655195,-46.691642
74,way,466030618,Sorvete McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6049408 -23.5495956, -46.6049273...",-23.549612,-46.604945
75,way,473171556,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.4148629 -23.4940303, -46.4148699...",-23.493993,-46.414790
76,way,485377612,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6916282 -23.6323604, -46.6915502...",-23.632370,-46.691471
82,way,520834260,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6816198 -23.5257951, -46.6814764...",-23.525963,-46.681633
84,way,521412312,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6572485 -23.576149, -46.6571615 ...",-23.576275,-46.657221
85,way,527216791,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6583399 -23.6523589, -46.6581964...",-23.652403,-46.658221
87,way,531288642,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6727779 -23.4785623, -46.6726794...",-23.478631,-46.672760
90,way,615957965,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.5803549 -23.4086245, -46.5802329...",-23.408751,-46.580328
91,way,618148590,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.639277 -23.5039166, -46.639223 -...",-23.504032,-46.639140
94,way,619988208,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7706757 -23.6660554, -46.7706967...",-23.666036,-46.770786
96,way,714038136,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6150364 -23.5015037, -46.6149877...",-23.501602,-46.615034
100,way,740690254,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6722637 -23.6440201, -46.6722745...",-23.643905,-46.672036
102,way,762725640,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7075343 -23.7447316, -46.707567 ...",-23.744827,-46.707429
103,way,764308008,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6811241 -23.6206616, -46.6812421...",-23.620816,-46.681091
104,way,765975918,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.4725045 -23.5397629, -46.4724722...",-23.539815,-46.472389
105,way,882079788,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.692722 -23.4970901, -46.6926234 ...",-23.496977,-46.692606
107,way,897093135,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.631741 -23.4826038, -46.6317485 ...",-23.482585,-46.631718
110,way,1030144858,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.61511 -23.5014798, -46.6150832 -...",-23.501455,-46.615100
114,way,1095525569,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6814194 -23.5893762, -46.6813611...",-23.589389,-46.681330
126,way,1268405160,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7123786 -23.5606584, -46.7123769...",-23.560701,-46.712289
132,way,1366064860,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7078697 -23.5950406, -46.7077721...",-23.594931,-46.707867
133,way,1422762843,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7071911 -23.576472, -46.7072342 ...",-23.576568,-46.707240
135,way,1457577418,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.6905379 -23.5946186, -46.6905556...",-23.594609,-46.690580
137,way,1483908892,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.7002393 -23.6952566, -46.7001244...",-23.695340,-46.700196
138,way,1495765197,McDonald's,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-46.4107606 -23.5815409, -46.4109402...",-23.581660,-46.410849

In [18]:
df_main = df_main.dropna(subset=['addr:street', 'addr:city', 'addr:postcode', 'addr:housenumber'])

In [19]:
df_main

,element,id,name,brand,addr:street,addr:housenumber,addr:city,addr:postcode,phone,website,geometry,lat,lon
0,node,142773190,McDonald's,McDonald's,Rua Henrique Schaumann,124,São Paulo,05413-010,NaN,NaN,POINT (-46.6782804 -23.5633723),-23.563372,-46.678280
2,node,2195123498,McDonald's,McDonald's,Avenida Paulista,2034,São Paulo,01310-200,NaN,NaN,POINT (-46.6593523 -23.5585802),-23.558580,-46.659352
4,node,2862747295,McDonald's,McDonald's,Rua Augusta,1858,São Paulo,01412-000,NaN,NaN,POINT (-46.6611783 -23.5588939),-23.558894,-46.661178
6,node,3415424081,McDonald's,McDonald's,Rua Oscar Freire,430,São Paulo,05406-000,NaN,NaN,POINT (-46.6749939 -23.5559542),-23.555954,-46.674994
8,node,4103937989,McDonald's,McDonald's,Rua Direita,33,São Paulo,01002-001,NaN,NaN,POINT (-46.6340033 -23.5489703),-23.548970,-46.634003
9,node,4230461279,McDonald's,McDonald's,Rua Silva Bueno,2185,São Paulo,04208-052,NaN,NaN,POINT (-46.6005897 -23.5978487),-23.597849,-46.600590
10,node,4552187868,McDonald's,McDonald's,Rua Maria Marcolina,440,São Paulo,03011-000,NaN,NaN,POINT (-46.6161189 -23.5381087),-23.538109,-46.616119
13,node,4964023947,McDonald's,McDonald's,Avenida Paulista,810,São Paulo,01310-100,NaN,NaN,POINT (-46.6505201 -23.566083),-23.566083,-46.650520
14,node,5084749337,McDonald's,McDonald's,Rua São Bento,215,São Paulo,01011-000,NaN,NaN,POINT (-46.6358014 -23.5471871),-23.547187,-46.635801
15,node,5091921398,McDonald's,McDonald's,Rua Vinte e Cinco de Março,767,São Paulo,01021-200,NaN,NaN,POINT (-46.632498 -23.5430315),-23.543032,-46.632498
16,node,5186280749,McDonald's,McDonald's,Rua Vinte e Cinco de Março,1109,São Paulo,01021-200,NaN,NaN,POINT (-46.6321726 -23.5399784),-23.539978,-46.632173
23,node,6711300983,McDonald's,McDonald's,Avenida Brigadeiro Faria Lima,1721,São Paulo,01452-001,NaN,NaN,POINT (-46.6896824 -23.572392),-23.572392,-46.689682
24,node,7128603055,McDonald's,McDonald's,Rua Barão de Itapetininga,26,São Paulo,01042-000,NaN,NaN,POINT (-46.6395816 -23.5453816),-23.545382,-46.639582
26,node,7233891172,McDonald's,McDonald's,Rua Serra de Bragança,437,São Paulo,03318-000,NaN,NaN,POINT (-46.5712756 -23.5454692),-23.545469,-46.571276
50,way,34379305,McDonald's,McDonald's,Avenida Vital Brasil,1256,São Paulo,05503-000,NaN,NaN,"POLYGON ((-46.7152313 -23.568928, -46.7151348 ...",-23.568837,-46.715137
55,way,244246052,McDonald's,McDonald's,Avenida Professor Luiz Ignácio Anhaia Mello,2230,São Paulo,03154-100,NaN,NaN,"POLYGON ((-46.5721661 -23.5834024, -46.5721664...",-23.583268,-46.572128
56,way,349199082,McDonald's,McDonald's,Avenida Nazaré,1664,São Paulo,04262-200,NaN,NaN,"POLYGON ((-46.6100979 -23.5988651, -46.6098365...",-23.598906,-46.609961
60,way,377530841,McDonald's,McDonald's,Avenida Luís Stamatis,129,São Paulo,02260-000,NaN,NaN,"POLYGON ((-46.5838934 -23.4673376, -46.5838353...",-23.467426,-46.583800
65,way,406706669,McDonald's,McDonald's,Avenida Paulista,1811,São Paulo,01311-200,NaN,NaN,"POLYGON ((-46.6579883 -23.5603643, -46.6579836...",-23.560442,-46.658085
66,way,428749183,McDonald's,McDonald's,Rua Domingos de Morais,1954,São Paulo,04036-000,NaN,NaN,"POLYGON ((-46.6368843 -23.5933042, -46.6368848...",-23.593380,-46.636972
68,way,431413727,McDonald's,McDonald's,Avenida da Liberdade,774,São Paulo,01502-001,NaN,NaN,"POLYGON ((-46.6380858 -23.5592924, -46.6380518...",-23.559312,-46.637938
72,way,466018976,McDonald's,McDonald's,Avenida Paes de Barros,2880,São Paulo,03149-000,NaN,NaN,"POLYGON ((-46.5875349 -23.5758865, -46.5875297...",-23.575987,-46.587558
77,way,490183403,McDonald's,McDonald's,Avenida Jaguaré,100,São Paulo,05346-000,NaN,NaN,"POLYGON ((-46.7452072 -23.5574438, -46.7454479...",-23.557550,-46.745301
79,way,509709633,McDonald's,McDonald's,Avenida Maria Luiza Americano,42,São Paulo,08275-001,NaN,NaN,"POLYGON ((-46.4813223 -23.5788216, -46.4814196...",-23.578742,-46.481371
81,way,520830534,McDonald's,McDonald's,Avenida Marquês de São Vicente,319,São Paulo,01139-001,NaN,https://www.mcdonalds.com.br/,"POLYGON ((-46.6631687 -23.5227105, -46.6631516...",-23.522509,-46.662970
83,way,521398695,Livraria da Vila,McDonald's,Avenida Moema,493,São Paulo,04077-022,+55 11 50523540,https://www.livrariadavila.com.br/,"POLYGON ((-46.6563602 -23.6059902, -46.6564448...",-23.606027,-46.656453
89,way,580895426,McDonald's,McDonald's,Avenida Sapopemba,8671,São Paulo,03989-000,NaN,NaN,"POLYGON ((-46.5172052 -23.5986312, -46.5172243...",-23.598682,-46.517322
92,way,618440554,McDonald's,McDonald's,Rua Professor Valério Giuli,104,São Paulo,02416-000,NaN,NaN,"POLYGON ((-46.6317504 -23.4821175, -46.631741 ...",-23.482281,-46.631720
93,way,619055861,McDonald's,McDonald's,Avenida Senador Teotônio Vilela,3347,São Paulo,04801-010,NaN,https://www.mcdonalds.com.br/,"POLYGON ((-46.6978724 -23.7302073, -46.6980315...",-23.730200,-46.697973
97,way,715131205,McDonald's,McDonald's,Rua Serra de Bragança,381,São Paulo,03318-000,NaN,NaN,"POLYGON ((-46.5714592 -23.5452198, -46.5714348...",-23.545359,-46.571488
99,way,732209894,McDonald's,McDonald's,Rua Funchal,500,São Paulo,04551-060,NaN,NaN,"POLYGON ((-46.6905775 -23.5949308, -46.6907029...",-23.594807,-46.690591
106,way,887514350,McDonald's,McDonald's,Rua Voluntários da Pátria,2273,São Paulo,02011-600,NaN,NaN,"POLYGON ((-46.6261775 -23.500117, -46.6261631 ...",-23.500219,-46.626025
108,way,921546899,McDonald's,McDonald's,Avenida Regente Feijó,1644,São Paulo,03342-000,NaN,NaN,"POLYGON ((-46.5616876 -23.5623909, -46.56158 -...",-23.562511,-46.561689
109,way,1013332958,McDonald's,McDonald's,Avenida Senador Teotônio Vilela,7908,São Paulo,04864-002,NaN,NaN,"POLYGON ((-46.7169834 -23.7647856, -46.717096 ...",-23.764892,-46.716988
111,way,1047427085,McDonald's,McDonald's,Rua Serra de Botucatu,2001,São Paulo,03317-001,NaN,NaN,"POLYGON ((-46.5515913 -23.5404552, -46.5515404...",-23.540441,-46.551492
112,way,1050645398,McDonald's,McDonald's,Avenida das Nações Unidas,22178,São Paulo,04696-005,NaN,NaN,"POLYGON ((-46.7001085 -23.6752075, -46.7000825...",-23.675243,-46.700222
113,way,1095473451,McDonald's,McDonald's,Avenida Ibirapuera,2645,São Paulo,04029-200,NaN,NaN,"POLYGON ((-46.6646763 -23.606955, -46.6648998 ...",-23.606768,-46.664758
116,way,1106064811,McDonald's,McDonald's,Alameda dos Jurupis,1948,São Paulo,04088-006,NaN,NaN,"POLYGON ((-46.6694148 -23.6130264, -46.6688628...",-23.613509,-46.669228
119,way,1178436298,McDonald's,McDonald's,Rua Vergueiro,205,São Paulo,01504-001,NaN,NaN,"POLYGON ((-46.6389776 -23.5639356, -46.6390023...",-23.564027,-46.638828
120,way,1180736143,McDonald's,McDonald's,Avenida Brigadeiro Faria Lima,1215,São Paulo,01452-002,NaN,NaN,"POLYGON ((-46.6921625 -23.5683113, -46.6921192...",-23.568361,-46.692151
121,way,1204235539,McDonald's,McDonald's,Rua Leite de Morais,107,São Paulo,02034-020,NaN,NaN,"POLYGON ((-46.6253638 -23.502927, -46.6252451 ...",-23.502985,-46.625317
122,way,1217659220,McDonald's,McDonald's,Avenida Santos Dumont,508,São Paulo,01101-000,NaN,NaN,"POLYGON ((-46.6303232 -23.5241441, -46.6303718...",-23.524297,-46.630189
123,way,1228944792,McDonald's,McDonald's,Rua Pamplona,734,São Paulo,01405-001,NaN,NaN,"POLYGON ((-46.6546638 -23.5644388, -46.6545842...",-23.564418,-46.654602
124,way,1240354054,McDonald's,McDonald's,Avenida Otaviano Alves de Lima,2888A,São Paulo,02701-000,NaN,NaN,"POLYGON ((-46.68453 -23.5082482, -46.6845572 -...",-23.508600,-46.684770
125,way,1240786947,McDonald's,McDonald's,Avenida Otaviano Alves de Lima,4694A,São Paulo,05101-100,NaN,NaN,"POLYGON ((-46.7036058 -23.5075096, -46.7037775...",-23.507203,-46.703837
127,way,1271065866,McDonald's,McDonald's,Praça da Liberdade,135,São Paulo,01503-010,NaN,NaN,"POLYGON ((-46.6351752 -23.5541649, -46.6350919...",-23.554201,-46.635144
129,way,1307489465,McDonald's,McDonald's,Avenida Angélica,1752,São Paulo,01228-200,NaN,NaN,"POLYGON ((-46.6589572 -23.5479718, -46.6588514...",-23.547776,-46.659101
130,way,1323882463,McDonald's,McDonald's,Avenida Ipiranga,764,São Paulo,01040-000,NaN,NaN,"POLYGON ((-46.6407251 -23.5429638, -46.6406653...",-23.542926,-46.640710
131,way,1355005743,McDonald's,McDonald's,Avenida Parada Pinto,1940,São Paulo,02611-001,NaN,NaN,"POLYGON ((-46.6525376 -23.4713605, -46.652418 ...",-23.471247,-46.652236
136,way,1459694614,McDonald's,McDonald's,Avenida Ermano Marchetti,457,São Paulo,05038-000,NaN,NaN,"POLYGON ((-46.6955117 -23.5158711, -46.6959633...",-23.515685,-46.695772

In [20]:
df_main = df_main.drop(columns=['element', 'phone', 'website', 'geometry'])

In [21]:
df_main

,id,name,brand,addr:street,addr:housenumber,addr:city,addr:postcode,lat,lon
0,142773190,McDonald's,McDonald's,Rua Henrique Schaumann,124,São Paulo,05413-010,-23.563372,-46.678280
2,2195123498,McDonald's,McDonald's,Avenida Paulista,2034,São Paulo,01310-200,-23.558580,-46.659352
4,2862747295,McDonald's,McDonald's,Rua Augusta,1858,São Paulo,01412-000,-23.558894,-46.661178
6,3415424081,McDonald's,McDonald's,Rua Oscar Freire,430,São Paulo,05406-000,-23.555954,-46.674994
8,4103937989,McDonald's,McDonald's,Rua Direita,33,São Paulo,01002-001,-23.548970,-46.634003
9,4230461279,McDonald's,McDonald's,Rua Silva Bueno,2185,São Paulo,04208-052,-23.597849,-46.600590
10,4552187868,McDonald's,McDonald's,Rua Maria Marcolina,440,São Paulo,03011-000,-23.538109,-46.616119
13,4964023947,McDonald's,McDonald's,Avenida Paulista,810,São Paulo,01310-100,-23.566083,-46.650520
14,5084749337,McDonald's,McDonald's,Rua São Bento,215,São Paulo,01011-000,-23.547187,-46.635801
15,5091921398,McDonald's,McDonald's,Rua Vinte e Cinco de Março,767,São Paulo,01021-200,-23.543032,-46.632498
16,5186280749,McDonald's,McDonald's,Rua Vinte e Cinco de Março,1109,São Paulo,01021-200,-23.539978,-46.632173
23,6711300983,McDonald's,McDonald's,Avenida Brigadeiro Faria Lima,1721,São Paulo,01452-001,-23.572392,-46.689682
24,7128603055,McDonald's,McDonald's,Rua Barão de Itapetininga,26,São Paulo,01042-000,-23.545382,-46.639582
26,7233891172,McDonald's,McDonald's,Rua Serra de Bragança,437,São Paulo,03318-000,-23.545469,-46.571276
50,34379305,McDonald's,McDonald's,Avenida Vital Brasil,1256,São Paulo,05503-000,-23.568837,-46.715137
55,244246052,McDonald's,McDonald's,Avenida Professor Luiz Ignácio Anhaia Mello,2230,São Paulo,03154-100,-23.583268,-46.572128
56,349199082,McDonald's,McDonald's,Avenida Nazaré,1664,São Paulo,04262-200,-23.598906,-46.609961
60,377530841,McDonald's,McDonald's,Avenida Luís Stamatis,129,São Paulo,02260-000,-23.467426,-46.583800
65,406706669,McDonald's,McDonald's,Avenida Paulista,1811,São Paulo,01311-200,-23.560442,-46.658085
66,428749183,McDonald's,McDonald's,Rua Domingos de Morais,1954,São Paulo,04036-000,-23.593380,-46.636972
68,431413727,McDonald's,McDonald's,Avenida da Liberdade,774,São Paulo,01502-001,-23.559312,-46.637938
72,466018976,McDonald's,McDonald's,Avenida Paes de Barros,2880,São Paulo,03149-000,-23.575987,-46.587558
77,490183403,McDonald's,McDonald's,Avenida Jaguaré,100,São Paulo,05346-000,-23.557550,-46.745301
79,509709633,McDonald's,McDonald's,Avenida Maria Luiza Americano,42,São Paulo,08275-001,-23.578742,-46.481371
81,520830534,McDonald's,McDonald's,Avenida Marquês de São Vicente,319,São Paulo,01139-001,-23.522509,-46.662970
83,521398695,Livraria da Vila,McDonald's,Avenida Moema,493,São Paulo,04077-022,-23.606027,-46.656453
89,580895426,McDonald's,McDonald's,Avenida Sapopemba,8671,São Paulo,03989-000,-23.598682,-46.517322
92,618440554,McDonald's,McDonald's,Rua Professor Valério Giuli,104,São Paulo,02416-000,-23.482281,-46.631720
93,619055861,McDonald's,McDonald's,Avenida Senador Teotônio Vilela,3347,São Paulo,04801-010,-23.730200,-46.697973
97,715131205,McDonald's,McDonald's,Rua Serra de Bragança,381,São Paulo,03318-000,-23.545359,-46.571488
99,732209894,McDonald's,McDonald's,Rua Funchal,500,São Paulo,04551-060,-23.594807,-46.690591
106,887514350,McDonald's,McDonald's,Rua Voluntários da Pátria,2273,São Paulo,02011-600,-23.500219,-46.626025
108,921546899,McDonald's,McDonald's,Avenida Regente Feijó,1644,São Paulo,03342-000,-23.562511,-46.561689
109,1013332958,McDonald's,McDonald's,Avenida Senador Teotônio Vilela,7908,São Paulo,04864-002,-23.764892,-46.716988
111,1047427085,McDonald's,McDonald's,Rua Serra de Botucatu,2001,São Paulo,03317-001,-23.540441,-46.551492
112,1050645398,McDonald's,McDonald's,Avenida das Nações Unidas,22178,São Paulo,04696-005,-23.675243,-46.700222
113,1095473451,McDonald's,McDonald's,Avenida Ibirapuera,2645,São Paulo,04029-200,-23.606768,-46.664758
116,1106064811,McDonald's,McDonald's,Alameda dos Jurupis,1948,São Paulo,04088-006,-23.613509,-46.669228
119,1178436298,McDonald's,McDonald's,Rua Vergueiro,205,São Paulo,01504-001,-23.564027,-46.638828
120,1180736143,McDonald's,McDonald's,Avenida Brigadeiro Faria Lima,1215,São Paulo,01452-002,-23.568361,-46.692151
121,1204235539,McDonald's,McDonald's,Rua Leite de Morais,107,São Paulo,02034-020,-23.502985,-46.625317
122,1217659220,McDonald's,McDonald's,Avenida Santos Dumont,508,São Paulo,01101-000,-23.524297,-46.630189
123,1228944792,McDonald's,McDonald's,Rua Pamplona,734,São Paulo,01405-001,-23.564418,-46.654602
124,1240354054,McDonald's,McDonald's,Avenida Otaviano Alves de Lima,2888A,São Paulo,02701-000,-23.508600,-46.684770
125,1240786947,McDonald's,McDonald's,Avenida Otaviano Alves de Lima,4694A,São Paulo,05101-100,-23.507203,-46.703837
127,1271065866,McDonald's,McDonald's,Praça da Liberdade,135,São Paulo,01503-010,-23.554201,-46.635144
129,1307489465,McDonald's,McDonald's,Avenida Angélica,1752,São Paulo,01228-200,-23.547776,-46.659101
130,1323882463,McDonald's,McDonald's,Avenida Ipiranga,764,São Paulo,01040-000,-23.542926,-46.640710
131,1355005743,McDonald's,McDonald's,Avenida Parada Pinto,1940,São Paulo,02611-001,-23.471247,-46.652236
136,1459694614,McDonald's,McDonald's,Avenida Ermano Marchetti,457,São Paulo,05038-000,-23.515685,-46.695772

In [22]:
df_main.isna().sum()

id                  0
name                0
brand               0
addr:street         0
addr:housenumber    0
addr:city           0
addr:postcode       0
lat                 0
lon                 0
dtype: int64

In [23]:
df_main = df_main.rename(columns={
    'addr:street': 'street',
    'addr:city': 'city',
    'addr:postcode': 'postcode',
    'addr:housenumber': 'housenumber'
})

In [25]:
df_main.to_csv(ROOT/"data/processed/osm_mcdonalds.csv", index=False)

In [27]:
df_dirty = pd.read_csv(ROOT/"data/raw/osm_mcdonalds_dirty.csv")
df_dirty.head()

,element,id,name,brand,addr:street,addr:housenumber,addr:city,addr:postcode,phone,website,geometry,lat,lon,is_duplicate
0,node,142773190,MCDONALD'S,McDonald's,Rua Henrique Schaumann,124,São Paulo,05413-010,NaN,NaN,POINT (-46.6782804 -23.5633723),-23.563847,-46.678505,1
1,node,865280465,Mc Donalds,McDonald's,Avenida Bernardino de Campos,307,NaN,04004-050,0800 888 1955,https://www.mcdonalds.com.br/,POINT (-46.6422711 -23.573439),-23.573799,-46.642669,1
2,node,2195123498,MCDONALD'S,McDonald's,Avenida Paulista,2034,São Paulo,01310-200,NaN,NaN,POINT (-46.6593523 -23.5585802),-23.558490,-46.659821,1
3,node,2428171364,MCDONALD'S,McDonald's,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-46.7024611 -23.5284532),-23.528735,-46.702456,1
4,node,2862747295,MCDONALD'S,McDonald's,Rua Augusta,1858,São Paulo,01412-000,NaN,NaN,POINT (-46.6611783 -23.5588939),-23.558833,-46.660962,1

In [28]:
df_dirty = df_dirty.drop(columns=['element', 'phone', 'website', 'geometry'])

In [29]:
df_dirty = df_dirty.rename(columns={
    'addr:street': 'street',
    'addr:city': 'city',
    'addr:postcode': 'postcode',
    'addr:housenumber': 'housenumber'
})

In [30]:
df_dirty

,id,name,brand,street,housenumber,city,postcode,lat,lon,is_duplicate
0,142773190,MCDONALD'S,McDonald's,Rua Henrique Schaumann,124,São Paulo,05413-010,-23.563847,-46.678505,1
1,865280465,Mc Donalds,McDonald's,Avenida Bernardino de Campos,307,NaN,04004-050,-23.573799,-46.642669,1
2,2195123498,MCDONALD'S,McDonald's,Avenida Paulista,2034,São Paulo,01310-200,-23.558490,-46.659821,1
3,2428171364,MCDONALD'S,McDonald's,NaN,NaN,NaN,NaN,-23.528735,-46.702456,1
4,2862747295,MCDONALD'S,McDonald's,Rua Augusta,1858,São Paulo,01412-000,-23.558833,-46.660962,1
...,...,...,...,...,...,...,...,...,...,...
134,1422916173,McDonald's,McDonald's,Avenida Professor Vicente Rao,1001,São Paulo,NaN,-23.632784,-46.679615,1
135,1457577418,McDonald's,McDonald's,NaN,NaN,NaN,NaN,-23.594695,-46.690450,1
136,1459694614,Mc Donalds,McDonald's,Avenida Ermano Marchetti,457,São Paulo,05038-000,-23.515467,-46.695888,1
137,1483908892,McDonald's,McDonald's,NaN,NaN,NaN,NaN,-23.695596,-46.700040,1
138,1495765197,MCDONALD'S,McDonald's,NaN,NaN,NaN,NaN,-23.581267,-46.410488,1

In [31]:
df_dirty.to_csv(ROOT/"data/processed/osm_mcdonalds_dirty.csv", index=False)